---
title: "Mean and Outliers After Curry"
format: html
editor: visual
---

## Reading Data

```{r}
#Taking into account players drafted after 2009
draft_data <- read.csv("../Final_project/renv/nbaplayersdraft.csv")
draft_after_curry <- draft_data[draft_data$year > 2009, ]
draft_after_curry

```

## Mean

```{r}
mean_3pt_percentage <- mean(draft_after_curry$X3_point_percentage, na.rm = TRUE)
print(paste("Mean Three Point Percentage After Curry:", mean_3pt_percentage))
```

## Outliers

```{r}
#using the IQR method, identify the outliers (players with 3pt percentage less than the lower bound or greater than upper bound)
Q1 <- quantile(draft_after_curry$X3_point_percentage, 0.40, na.rm = TRUE)
Q3 <- quantile(draft_after_curry$X3_point_percentage, 0.60, na.rm = TRUE)
IQR <- Q3 - Q1

lower_bound <- Q1 - 1.5 * IQR
upper_bound <- Q3 + 1.5 * IQR
print(lower_bound)
print(upper_bound)

outliers <- draft_after_curry[draft_after_curry$X3_point_percentage < lower_bound | draft_after_curry$X3_point_percentage > upper_bound, ]
outliers <- outliers[!is.na(outliers$X3_point_percentage), ]

outliers #subset of outliers
```

## Veterans (1000 games or more) With Smallest 3pt Percentage

```{r}
veterans <- draft_data[draft_data$games >= 1000, ]
veterans <- veterans[!is.na(veterans$X3_point_percentage), ]
#Veterans whose 3pt percentage falls under the lower bound are listed in the veterans_least_3pt_percentage subset
veterans_least_index <- which.min(veterans$X3_point_percentage)
worst_veteran <- veterans[veterans_least_index, ]
worst_veteran
```

```{r}
library(ggplot2)
three_pt_scatterplot <- ggplot(veterans, aes(x = average_minutes_played, y = X3_point_percentage)) + 
  geom_point(color = "blue") +
  geom_point(data = worst_veteran, aes(x = average_minutes_played, y = X3_point_percentage), color = "red", size = 3) + 
  labs(title = "3 Point Percentage (After Curry) vs. Average Minutes Played",
       x = "Average Minutes Played,",
       y = "3-Point Percentage") + 
  theme_minimal()

three_pt_scatterplot



```
